###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.3"

networks:
  custom_network:
    external:
      name: network_for_app

services:
  memcached:
    image: memcached:alpine
    container_name: app-memcached
    ports:
      - '11212:11211'
    environment:
      - MEMCACHED_CACHE_SIZE=1024
      - MEMCACHED_CONN_LIMIT=1024
    networks:
      custom_network:
        aliases:
          - memcached

  redis:
    image: redis:alpine
    container_name: app-redis
    ports:
      - '6380:6379'
    networks:
      custom_network:
        aliases:
          - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: app-rabbitmq
    environment:
      - RABBITMQ_ENABLE_MANAGEMENT_PLUGIN=true
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=256MiB
    ports:
      - "15673:15672"
      - "5673:5672"
    networks:
      custom_network:
        aliases:
          - rabbitmq

  mysql:
    image: mysql:latest
    container_name: app-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=database
      - MYSQL_USER=user_database
      - MYSQL_PASSWORD=pass_database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./services_config/data:/var/lib/mysql
      - ./services_config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3309:3306"
    networks:
      custom_network:
        aliases:
          - mysql

  php-fpm:
    build:
      context: .
      dockerfile: ./services_config/php-fpm/Dockerfile
    container_name: app-php-fpm
    hostname: app-php-fpm
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:cached
      - ./services_config/php-fpm/php.ini:/etc/php/7.3/fpm/php.ini
      - ./services_config/php-fpm/php.ini:/etc/php/7.3/cli/php.ini
      - ./services_config/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ./services_config/php-fpm/php-ini-overrides.ini:/etc/php/7.3/cli/conf.d/99-overrides.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=docker"
      APP_ENV: "dev"
    depends_on:
      - mysql
    networks:
      custom_network:
        aliases:
          - app-php-fpm

  webserver:
    image: nginx:alpine
    container_name: app-webserver
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:cached
      - ./services_config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9990:80"
    depends_on:
      - php-fpm
    networks:
      custom_network:
        aliases:
          - webserver
